### ISSUE TITLE
10: As a user, I want to be able to request translations of the chat box content during online matches so that I can understand and communicate effectively with players who speak different languages.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#10]
- [x] sopra-fs24-group-08/sopra-fs24-group-08-client#17
- [x] sopra-fs24-group-08/sopra-fs24-group-08-server#45
- [x] sopra-fs24-group-08/sopra-fs24-group-08-client#18
- [x] sopra-fs24-group-08/sopra-fs24-group-08-server#47

**Comment by Davtan00** [comment]
2bf441b Setup external API Google Cloud Translation service and controller

**Comment by Davtan00** [comment]
778cde2 closed
