### ISSUE TITLE
12: As a user, I want to be able to play card games with my friends over a local network or Bluetooth when there is no internet connection, so that I can enjoy gaming sessions and competitive fun with friends wherever we are.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#12]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-server#51
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#21
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#22
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-server#54
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#23

**Comment by CindyChen-1999** [comment]
We can eliminate this story
