### ISSUE TITLE
13: As a user, I want to stop the game and let the opponent win at any time to deal with circumstances like I already know I’ll fail or have some emergency without losing my data.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#13]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#24
- [x] sopra-fs24-group-08/sopra-fs24-group-08-server#57
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#25
