### ISSUE TITLE
14: As a user, I want to have a web page of my own profile and be able to add other users as friends to enable the system record my achievement and make friends.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#14]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#26
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#27
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#28
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#29

**Comment by Davtan00** [comment]
Main part server side done in 2d2d38d , rest in c2a7be3
