### ISSUE TITLE
16: As a user, I want a spectator mode in the game, so that I can watch ongoing games and return to my previous page after the game ends.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#16]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-server#66
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#30
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#31
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#32
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#33
