### ISSUE TITLE
02: As a user, I want to be able to choose if I go first or second and then depending on that receive 2/3 cards.

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#2]
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#4
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-client#5
- [ ] sopra-fs24-group-08/sopra-fs24-group-08-server#24

**Comment by Davtan00** [comment]
2bf441b
