### ISSUE TITLE
08: As a user, I want to see the percentage of loading process after I click ”Start game”, so that I can estimate how much time I still need to actually get started or if anything goes wrong -> Too Fast to display it

### ISSUE THREAD

**Issue by LooPyt** [sopra-fs24-group-08/sopra-fs24-group-08-server#8]
- [x] sopra-fs24-group-08/sopra-fs24-group-08-client#14
- [x] sopra-fs24-group-08/sopra-fs24-group-08-client#15
- [x] sopra-fs24-group-08/sopra-fs24-group-08-server#41
